---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(gapminder)
head(gapminder)
```

```{r}
gapminder %>%
  filter(
    continent == "Americas",
    year %in% c(2007)
  ) %>%
  select(country, lifeExp)
```
```{r}
continent_year_index <- which(gapminder["continent"] == "Americas" & gapminder["year"] == 2007)
gapminder[continent_year_index, c("country", "lifeExp")]
```
```{r}
gapminder %>%
  filter(year == 2007) %>%
  mutate(gdp = gdpPercap * pop) %>%
  select(country, gdp) %>%
  arrange(desc(gdp)) %>%
  head()
```
```{r}
gapminder %>%
  arrange(year) 
```
```{r}
gapminder %>%
  group_by(year) %>%
  summarise(mean(lifeExp)) %>%
  ungroup()
```
```{r}
gapminder %>%
  filter(year == 2007) %>%
  group_by(continent) %>%
  filter(lifeExp > mean(lifeExp))  %>%
  filter(continent == "Asia")
```
```{r}
gapminder %>%
  filter(continent == "Asia", year == 2007) %>%
  filter(lifeExp > mean(lifeExp)) %>%
  arrange(desc(lifeExp))
```
```{r}
gapminder %>%
  filter(year == 2007) %>%
  group_by(continent) %>%
  mutate(avg_life_expectancy = mean(lifeExp)) %>%
  ungroup() %>%
  mutate(diff_life_exp = lifeExp - avg_life_expectancy) %>%
  filter(diff_life_exp > 0) %>%
  select(country, diff_life_exp) %>%
  arrange(desc(diff_life_exp))
```

